#!/bin/bash
# Dock manager for nwg-dock-hyprland — ensures single instance and auto color sync

DOCK_BIN="nwg-dock-hyprland"
DOCK_CONFIG="$HOME/.config/nwg-dock-hyprland/config"
STYLE_FILE="$HOME/.config/nwg-dock-hyprland/style.css"
LOG_FILE="/tmp/nwg-dock.log"
LOCK_FILE="/tmp/nwg-dock.lock"

# Kill any existing dock instance before relaunching
if pgrep -f "$DOCK_BIN" >/dev/null 2>&1; then
    pkill -f "$DOCK_BIN"
    sleep 0.3
fi

# Load Pywal colors if available
if [[ -f "$HOME/.cache/wal/colors.sh" ]]; then
    source "$HOME/.cache/wal/colors.sh"

    # Convert hex → rgba with transparency
    hex_to_rgba() {
        local hex=${1#"#"}
        local r=$((16#${hex:0:2}))
        local g=$((16#${hex:2:2}))
        local b=$((16#${hex:4:2}))
        local a=${2:-0.35}
        echo "rgba($r,$g,$b,$a)"
    }

    bg_rgba=$(hex_to_rgba "$background" 0.35)
    accent_rgba=$(hex_to_rgba "$color1" 0.55)
    border_rgba=$(hex_to_rgba "$color8" 0.3)

    # Write generated CSS
    mkdir -p "$(dirname "$STYLE_FILE")"
    cat > "$STYLE_FILE" <<EOF
/* Auto-generated by dock-manager.sh — Pywal Glass Theme */

window {
    background-color: transparent;
}

.dock {
    background-color: $bg_rgba;
    border-radius: 14px;
    border: 1px solid $border_rgba;
    backdrop-filter: blur(18px);
    box-shadow: 0px 6px 18px rgba(0, 0, 0, 0.35);
    padding: 6px;
}

.dock button {
    background: transparent;
    border: none;
    margin: 3px;
    padding: 4px;
}

.dock button:hover {
    background-color: $accent_rgba;
    border-radius: 10px;
}
EOF
else
    echo "⚠️ No Pywal colors found — using fallback styling"
fi

# Launch dock safely (top, visible, single instance)
"$DOCK_BIN" -m -r -l top -x -c "$DOCK_CONFIG" >"$LOG_FILE" 2>&1 &

echo "✅ Dock launched. Logs → $LOG_FILE"
