#!/bin/bash
# ~/.config/hypr/scripts/dock-manager.sh
# Auto-refresh for nwg-dock-hyprland color theme (Pywal-integrated, GTK-safe)

CONFIG_DIR="$HOME/.config/nwg-dock-hyprland"
STYLE_FILE="$CONFIG_DIR/style.css"
LOG_FILE="/tmp/nwg-dock.log"

# Load Pywal colors
if [ -f "$HOME/.cache/wal/colors.sh" ]; then
    source "$HOME/.cache/wal/colors.sh"
else
    echo "No pywal colors found, using defaults."
    background="#1e1e2e"
    color0="#313244"
    foreground="#cdd6f4"
    color12="#89b4fa"
fi

mkdir -p "$CONFIG_DIR"

# Convert hex (#RRGGBB) to rgba() for transparency
hex_to_rgba() {
    local hex="$1"
    local alpha="$2"
    hex="${hex#\#}"
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))
    echo "rgba(${r},${g},${b},${alpha})"
}

BG_RGBA=$(hex_to_rgba "$background" 0.5)
HOVER_RGBA=$(hex_to_rgba "$color12" 0.2)

# ✅ Generate GTK-compatible CSS
cat > "$STYLE_FILE" <<EOF
/* Auto-generated by dock-manager.sh — Pywal Glass Theme */

@define-color background ${BG_RGBA};
@define-color bordercolor ${color0};
@define-color foreground ${foreground};
@define-color accent ${color12};
@define-color hovercolor ${HOVER_RGBA};

window {
    background-color: @background;
    border-radius: 16px;
    border: 1px solid @bordercolor;
    margin: 4px;
    padding: 4px;
    box-shadow: 0 0 12px rgba(0, 0, 0, 0.25);
}

button {
    background: transparent;
    border: none;
    margin: 2px;
    padding: 3px;
    border-radius: 16px;
    transition: all 0.2s ease-in-out;
}

button:hover {
    background-color: @hovercolor;
}

button:active,
button:checked {
    background-color: @accent;
}

label {
    color: @foreground;
    font-size: 10pt;
    font-weight: 500;
}

.image {
    border-radius: 8px;
    margin: 3px;
}
EOF

# 🧩 Restart dock cleanly
pkill -f nwg-dock-hyprland 2>/dev/null
sleep 0.3
#nwg-dock-hyprland -l top -x -c "$CONFIG_DIR/config" >"$LOG_FILE" 2>&1 &
#nwg-dock-hyprland -config "$CONFIG_DIR/config" >"$LOG_FILE" 2>&1 &
#nwg-dock-hyprland -l top -x -c "$CONFIG_DIR/config" >"$LOG_FILE" 2>&1 &
nwg-dock-hyprland \
    -p bottom \
    -l overlay \
    -mt 10 \
    -mb 10 \
    -a center \
    -s ~/.config/nwg-dock-hyprland/style.css \
    -debug &

disown

echo "[dock-manager] nwg-dock-hyprland restarted with Pywal theme"
